# MySQL Configuration

- name: Update DNF Package repository cache
  dnf:
    update_cache: True

- name: Install MySQL Packages
  yum: name={{ item }} update_cache=yes state=latest
  loop: [ 'mysql-server', 'php-mysqlnd', 'python3-PyMySQL' ]

- name: Install MySQL client on CentOS 8
  dnf:
    name: mysql
    state: present

- name: Start mysqld service
  systemd: name=mysqld state=started enabled=yes

- name: Set MySQL root Password
  mysql_user:
    login_host: 'localhost'
    login_user: 'root'
    login_password: '{{mysql_root_old_password}}'
    name: 'root'
    password: '{{ mysql_root_password }}'
    state: present

- name: Start mysqld service
  systemd: name=mysqld state=restarted enabled=yes

- name: Creates database for WordPress
  mysql_db:
    name: "{{ mysql_db }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create MySQL user for WordPress
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    priv: "{{ mysql_db }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"